# Site settings
title: Ryan McCune
email: rmccune@ncsu.edu
description: "PhD Student in Civil Engineering concentrating in Coastal Engineering at North Carolina State University, focusing on chronic coastal flooding."
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://rtmccune.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Social links
github_username: rtmccune # Replace with your GitHub username
linkedin_username: ryan-mccune # Replace with your LinkedIn profile part
scholar_id: citations?user=CnYIFHQAAAAJ&hl=en&oi=ao # Replace with your Google Scholar ID

# Navigation (matches the example visual)
header_pages:
  - bio.md
  - research.md
  - sensordev.md
  - publications.md
  - presentations.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# files in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
